"""
Generate complete HSK 2-5 character datasets for the game.
Outputs JSON files to godot-project/data/hskN/characters.json
and updates radical data.

Usage: python tools/generate_hsk_data.py
"""
import json
import os

# HSK 2 characters (new in HSK 2, ~150 characters)
# Format: (character, pinyin, tone, meaning, radicals, components, is_radical, frequency_rank)
HSK2_CHARS = [
    ("吧", "ba", 0, "particle (suggestion)", ["口"], ["口", "巴"], False, 95),
    ("白", "bái", 2, "white, blank", [], [], True, 178),
    ("百", "bǎi", 3, "hundred", ["白"], ["一", "白"], False, 234),
    ("帮", "bāng", 1, "to help", ["巾"], ["邦", "巾"], False, 567),
    ("报", "bào", 4, "newspaper, to report", ["扌"], ["扌", "报"], False, 312),
    ("比", "bǐ", 3, "to compare", [], [], True, 189),
    ("别", "bié", 2, "don't, other", ["刂"], ["另", "刂"], False, 156),
    ("宾", "bīn", 1, "guest", ["宀"], ["宀", "兵"], False, 890),
    ("病", "bìng", 4, "illness, sick", ["疒"], ["疒", "丙"], False, 478),
    ("长", "cháng", 2, "long", [], [], True, 67),
    ("唱", "chàng", 4, "to sing", ["口"], ["口", "昌"], False, 876),
    ("出", "chū", 1, "to go out", [], [], True, 23),
    ("穿", "chuān", 1, "to wear", ["穴"], ["穴", "牙"], False, 543),
    ("次", "cì", 4, "time (measure word)", ["欠"], ["冫", "欠"], False, 198),
    ("从", "cóng", 2, "from", [], [], True, 45),
    ("错", "cuò", 4, "wrong, mistake", ["钅"], ["钅", "昔"], False, 456),
    ("打", "dǎ", 3, "to hit, to play", ["扌"], ["扌", "丁"], False, 87),
    ("大", "dà", 4, "big, large", [], [], True, 18),
    ("到", "dào", 4, "to arrive", ["刂"], ["至", "刂"], False, 14),
    ("得", "de", 0, "particle (degree)", [], [], False, 11),
    ("等", "děng", 3, "to wait, class", ["竹"], ["竹", "寺"], False, 267),
    ("弟", "dì", 4, "younger brother", ["弓"], ["丷", "弓"], False, 678),
    ("第", "dì", 4, "ordinal prefix", ["竹"], ["竹", "弟"], False, 145),
    ("懂", "dǒng", 3, "to understand", ["忄"], ["忄", "董"], False, 789),
    ("对", "duì", 4, "correct, toward", ["又"], ["又", "寸"], False, 28),
    ("房", "fáng", 2, "room, house", ["户"], ["户", "方"], False, 356),
    ("非", "fēi", 1, "not, non-", [], [], True, 234),
    ("服", "fú", 2, "clothes, to serve", ["月"], ["月", "又"], False, 445),
    ("该", "gāi", 1, "should, ought to", ["讠"], ["讠", "亥"], False, 267),
    ("告", "gào", 4, "to tell, to inform", ["口"], ["牛", "口"], False, 345),
    ("哥", "gē", 1, "older brother", ["口"], ["口", "可"], False, 567),
    ("给", "gěi", 3, "to give", ["纟"], ["纟", "合"], False, 56),
    ("公", "gōng", 1, "public", [], [], True, 89),
    ("共", "gòng", 4, "together", [], [], False, 234),
    ("狗", "gǒu", 3, "dog", ["犭"], ["犭", "句"], False, 876),
    ("贵", "guì", 4, "expensive, noble", ["贝"], ["中", "贝"], False, 567),
    ("过", "guò", 4, "to pass, particle", ["辶"], ["辶", "寸"], False, 29),
    ("孩", "hái", 2, "child", ["子"], ["子", "亥"], False, 345),
    ("还", "hái", 2, "still, also", ["辶"], ["辶", "不"], False, 34),
    ("好", "hǎo", 3, "good", ["女"], ["女", "子"], False, 36),
    ("号", "hào", 4, "number", ["口"], ["口", "丂"], False, 345),
    ("黑", "hēi", 1, "black", [], [], True, 456),
    ("红", "hóng", 2, "red", ["纟"], ["纟", "工"], False, 567),
    ("后", "hòu", 4, "after, behind", ["口"], ["厂", "口"], False, 37),
    ("花", "huā", 1, "flower, to spend", ["艹"], ["艹", "化"], False, 345),
    ("欢", "huān", 1, "happy, joyful", ["欠"], ["又", "欠"], False, 456),
    ("回", "huí", 2, "to return", ["囗"], ["囗", "口"], False, 67),
    ("会", "huì", 4, "can, meeting", [], [], False, 15),
    ("火", "huǒ", 3, "fire", [], [], True, 234),
    ("鸡", "jī", 1, "chicken", ["鸟"], ["又", "鸟"], False, 876),
    ("机", "jī", 1, "machine, opportunity", ["木"], ["木", "几"], False, 78),
    ("件", "jiàn", 4, "item (measure word)", ["亻"], ["亻", "牛"], False, 345),
    ("教", "jiāo", 1, "to teach", ["攵"], ["孝", "攵"], False, 267),
    ("姐", "jiě", 3, "older sister", ["女"], ["女", "且"], False, 567),
    ("介", "jiè", 4, "to introduce", [], [], False, 567),
    ("进", "jìn", 4, "to enter", ["辶"], ["辶", "井"], False, 78),
    ("近", "jìn", 4, "near", ["辶"], ["辶", "斤"], False, 345),
    ("就", "jiù", 4, "then, at once", [], [], False, 16),
    ("觉", "jué", 2, "to feel, to sleep", ["见"], ["学", "见"], False, 189),
    ("开", "kāi", 1, "to open", [], [], True, 56),
    ("考", "kǎo", 3, "to test, exam", [], [], False, 456),
    ("可", "kě", 3, "can, may", ["口"], ["丁", "口"], False, 26),
    ("课", "kè", 4, "class, lesson", ["讠"], ["讠", "果"], False, 567),
    ("快", "kuài", 4, "fast, happy", ["忄"], ["忄", "夬"], False, 234),
    ("离", "lí", 2, "to leave, from", [], [], False, 345),
    ("两", "liǎng", 3, "two (amount)", [], [], False, 89),
    ("零", "líng", 2, "zero", ["雨"], ["雨", "令"], False, 567),
    ("路", "lù", 4, "road, path", ["足"], ["足", "各"], False, 234),
    ("旅", "lǚ", 3, "to travel", ["方"], ["方", "亻"], False, 456),
    ("妈", "mā", 1, "mother", ["女"], ["女", "马"], False, 234),
    ("马", "mǎ", 3, "horse", [], [], True, 345),
    ("买", "mǎi", 3, "to buy", [], [], False, 456),
    ("卖", "mài", 4, "to sell", [], [], False, 567),
    ("慢", "màn", 4, "slow", ["忄"], ["忄", "曼"], False, 567),
    ("忙", "máng", 2, "busy", ["忄"], ["忄", "亡"], False, 456),
    ("每", "měi", 3, "every, each", [], [], False, 189),
    ("妹", "mèi", 4, "younger sister", ["女"], ["女", "未"], False, 678),
    ("门", "mén", 2, "door, gate", [], [], True, 234),
    ("面", "miàn", 4, "face, noodles", [], [], True, 156),
    ("男", "nán", 2, "male", ["田"], ["田", "力"], False, 345),
    ("您", "nín", 2, "you (polite)", ["忄"], ["你", "心"], False, 567),
    ("牛", "niú", 2, "cow, ox", [], [], True, 678),
    ("女", "nǚ", 3, "woman, female", [], [], True, 156),
    ("旁", "páng", 2, "beside, next to", ["方"], ["立", "方"], False, 567),
    ("跑", "pǎo", 3, "to run", ["足"], ["足", "包"], False, 567),
    ("便", "pián", 2, "cheap, convenient", ["亻"], ["亻", "更"], False, 345),
    ("票", "piào", 4, "ticket", ["示"], ["西", "示"], False, 567),
    ("妻", "qī", 1, "wife", ["女"], ["女", "一"], False, 678),
    ("起", "qǐ", 3, "to rise, to start", ["走"], ["走", "己"], False, 67),
    ("千", "qiān", 1, "thousand", [], [], True, 345),
    ("铅", "qiān", 1, "lead (metal)", ["钅"], ["钅", "几"], False, 890),
    ("清", "qīng", 1, "clear, clean", ["氵"], ["氵", "青"], False, 456),
    ("请", "qǐng", 3, "please, to invite", ["讠"], ["讠", "青"], False, 267),
    ("去", "qù", 4, "to go", [], [], True, 19),
    ("让", "ràng", 4, "to let, to allow", ["讠"], ["讠", "上"], False, 234),
    ("日", "rì", 4, "day, sun", [], [], True, 67),
    ("上", "shàng", 4, "up, above", [], [], True, 9),
    ("身", "shēn", 1, "body", [], [], True, 234),
    ("生", "shēng", 1, "to be born, life", [], [], True, 56),
    ("时", "shí", 2, "time", ["日"], ["日", "寸"], False, 25),
    ("事", "shì", 4, "thing, matter", [], [], False, 34),
    ("手", "shǒu", 3, "hand", [], [], True, 156),
    ("瘦", "shòu", 4, "thin", ["疒"], ["疒", "叟"], False, 789),
    ("说", "shuō", 1, "to say, to speak", ["讠"], ["讠", "兑"], False, 12),
    ("送", "sòng", 4, "to send, to give", ["辶"], ["辶", "关"], False, 456),
    ("虽", "suī", 1, "although", ["虫"], ["虫", "口"], False, 567),
    ("它", "tā", 1, "it", ["宀"], ["宀", "匕"], False, 234),
    ("题", "tí", 2, "topic, question", ["页"], ["是", "页"], False, 345),
    ("踢", "tī", 1, "to kick", ["足"], ["足", "易"], False, 890),
    ("体", "tǐ", 3, "body", ["亻"], ["亻", "本"], False, 234),
    ("条", "tiáo", 2, "strip (MW)", ["木"], ["夂", "木"], False, 345),
    ("同", "tóng", 2, "same", ["口"], ["冂", "口"], False, 89),
    ("外", "wài", 4, "outside", [], [], True, 67),
    ("完", "wán", 2, "to finish, complete", ["宀"], ["宀", "元"], False, 156),
    ("玩", "wán", 2, "to play", ["王"], ["王", "元"], False, 456),
    ("晚", "wǎn", 3, "late, evening", ["日"], ["日", "免"], False, 345),
    ("往", "wǎng", 3, "toward", ["彳"], ["彳", "王"], False, 234),
    ("为", "wèi", 4, "for, because", [], [], False, 13),
    ("问", "wèn", 4, "to ask", ["口"], ["门", "口"], False, 78),
    ("洗", "xǐ", 3, "to wash", ["氵"], ["氵", "先"], False, 567),
    ("希", "xī", 1, "to hope", [], [], False, 345),
    ("习", "xí", 2, "to practice", [], [], False, 234),
    ("先", "xiān", 1, "first, before", [], [], True, 145),
    ("现", "xiàn", 4, "now, present", ["王"], ["王", "见"], False, 56),
    ("向", "xiàng", 4, "toward, direction", [], [], True, 234),
    ("笑", "xiào", 4, "to laugh, to smile", ["竹"], ["竹", "夭"], False, 345),
    ("新", "xīn", 1, "new", ["斤"], ["亲", "斤"], False, 78),
    ("姓", "xìng", 4, "surname", ["女"], ["女", "生"], False, 567),
    ("休", "xiū", 1, "to rest", ["亻"], ["亻", "木"], False, 456),
    ("雪", "xuě", 3, "snow", ["雨"], ["雨", "彐"], False, 678),
    ("眼", "yǎn", 3, "eye", ["目"], ["目", "艮"], False, 234),
    ("要", "yào", 4, "to want, important", [], [], False, 10),
    ("也", "yě", 3, "also", [], [], True, 17),
    ("已", "yǐ", 3, "already", [], [], True, 67),
    ("意", "yì", 4, "meaning, intention", ["忄"], ["音", "心"], False, 89),
    ("因", "yīn", 1, "because", ["囗"], ["囗", "大"], False, 145),
    ("阴", "yīn", 1, "cloudy, shade", ["阝"], ["阝", "月"], False, 678),
    ("游", "yóu", 2, "to swim, to travel", ["氵"], ["氵", "方"], False, 456),
    ("鱼", "yú", 2, "fish", [], [], True, 567),
    ("远", "yuǎn", 3, "far", ["辶"], ["辶", "元"], False, 345),
    ("运", "yùn", 4, "luck, to transport", ["辶"], ["辶", "云"], False, 345),
    ("再", "zài", 4, "again", [], [], True, 89),
    ("早", "zǎo", 3, "early, morning", ["日"], ["日", "十"], False, 234),
    ("张", "zhāng", 1, "MW for flat things", ["弓"], ["弓", "长"], False, 345),
    ("找", "zhǎo", 3, "to look for", ["扌"], ["扌", "戈"], False, 267),
    ("着", "zhe", 0, "particle (ongoing)", [], [], False, 20),
    ("真", "zhēn", 1, "real, true", ["目"], ["直", "八"], False, 89),
    ("正", "zhèng", 4, "correct, just", [], [], True, 78),
    ("知", "zhī", 1, "to know", ["矢"], ["矢", "口"], False, 34),
    ("准", "zhǔn", 3, "accurate, to allow", ["冫"], ["冫", "隹"], False, 345),
    ("走", "zǒu", 3, "to walk", [], [], True, 156),
    ("最", "zuì", 4, "most", ["日"], ["日", "取"], False, 89),
    ("左", "zuǒ", 3, "left", [], [], True, 345),
    ("做", "zuò", 4, "to do, to make", ["亻"], ["亻", "故"], False, 56),
]

# HSK 3 characters (new in HSK 3, ~150 characters)
HSK3_CHARS = [
    ("啊", "a", 0, "particle (exclamation)", ["口"], ["口", "阿"], False, 145),
    ("安", "ān", 1, "safe, peaceful", ["宀"], ["宀", "女"], False, 234),
    ("把", "bǎ", 3, "to hold, MW", ["扌"], ["扌", "巴"], False, 45),
    ("搬", "bān", 1, "to move (objects)", ["扌"], ["扌", "般"], False, 789),
    ("办", "bàn", 4, "to handle", [], [], False, 178),
    ("半", "bàn", 4, "half", [], [], True, 234),
    ("包", "bāo", 1, "to wrap, bag", ["勹"], ["勹", "巳"], False, 345),
    ("北", "běi", 3, "north", [], [], True, 156),
    ("被", "bèi", 4, "by (passive), quilt", ["衤"], ["衤", "皮"], False, 89),
    ("鼻", "bí", 2, "nose", [], [], True, 789),
    ("变", "biàn", 4, "to change", [], [], False, 178),
    ("表", "biǎo", 3, "surface, watch, form", [], [], False, 178),
    ("冰", "bīng", 1, "ice", ["冫"], ["冫", "水"], False, 567),
    ("才", "cái", 2, "just now, talent", [], [], True, 89),
    ("菜", "cài", 4, "dish, vegetable", ["艹"], ["艹", "采"], False, 456),
    ("草", "cǎo", 3, "grass", ["艹"], ["艹", "早"], False, 567),
    ("层", "céng", 2, "layer, floor", ["尸"], ["尸", "云"], False, 456),
    ("差", "chà", 4, "to lack, poor", [], [], False, 234),
    ("超", "chāo", 1, "to exceed, super", ["走"], ["走", "召"], False, 345),
    ("成", "chéng", 2, "to become, success", [], [], True, 45),
    ("城", "chéng", 2, "city", ["土"], ["土", "成"], False, 234),
    ("迟", "chí", 2, "late", ["辶"], ["辶", "尺"], False, 567),
    ("除", "chú", 2, "to remove, except", ["阝"], ["阝", "余"], False, 345),
    ("船", "chuán", 2, "boat, ship", ["舟"], ["舟", "几"], False, 456),
    ("春", "chūn", 1, "spring (season)", ["日"], ["三", "日"], False, 345),
    ("词", "cí", 2, "word", ["讠"], ["讠", "司"], False, 456),
    ("聪", "cōng", 1, "clever, smart", ["耳"], ["耳", "总"], False, 678),
    ("答", "dá", 2, "to answer", ["竹"], ["竹", "合"], False, 345),
    ("带", "dài", 4, "to bring, belt", [], [], False, 234),
    ("担", "dān", 1, "to carry, worry", ["扌"], ["扌", "旦"], False, 456),
    ("蛋", "dàn", 4, "egg", ["虫"], ["虫", "疋"], False, 567),
    ("当", "dāng", 1, "when, to serve as", [], [], False, 78),
    ("灯", "dēng", 1, "lamp, light", ["火"], ["火", "丁"], False, 567),
    ("地", "dì", 4, "earth, ground", ["土"], ["土", "也"], False, 34),
    ("调", "diào", 4, "to adjust, tone", ["讠"], ["讠", "周"], False, 345),
    ("东", "dōng", 1, "east", [], [], True, 89),
    ("冬", "dōng", 1, "winter", ["冫"], ["夂", "冫"], False, 456),
    ("动", "dòng", 4, "to move", ["力"], ["云", "力"], False, 78),
    ("短", "duǎn", 3, "short", ["矢"], ["矢", "豆"], False, 345),
    ("段", "duàn", 4, "section, paragraph", [], [], False, 345),
    ("锻", "duàn", 4, "to forge, exercise", ["钅"], ["钅", "段"], False, 678),
    ("多", "duō", 1, "many, much", [], [], True, 22),
    ("饿", "è", 4, "hungry", ["食"], ["食", "我"], False, 789),
    ("耳", "ěr", 3, "ear", [], [], True, 567),
    ("发", "fā", 1, "to send, hair", [], [], False, 45),
    ("方", "fāng", 1, "direction, square", [], [], True, 89),
    ("放", "fàng", 4, "to put, to release", ["攵"], ["方", "攵"], False, 178),
    ("费", "fèi", 4, "expense, fee", ["贝"], ["弗", "贝"], False, 345),
    ("分", "fēn", 1, "to divide, minute", ["刂"], ["八", "刂"], False, 45),
    ("附", "fù", 4, "to attach, nearby", ["阝"], ["阝", "付"], False, 567),
    ("干", "gān", 1, "dry, to do", [], [], True, 89),
    ("感", "gǎn", 3, "to feel, emotion", ["忄"], ["咸", "心"], False, 89),
    ("刚", "gāng", 1, "just now, hard", ["刂"], ["冈", "刂"], False, 234),
    ("高", "gāo", 1, "tall, high", [], [], True, 78),
    ("根", "gēn", 1, "root, MW", ["木"], ["木", "艮"], False, 234),
    ("更", "gèng", 4, "even more", [], [], False, 78),
    ("关", "guān", 1, "to close, related", [], [], False, 56),
    ("管", "guǎn", 3, "to manage, pipe", ["竹"], ["竹", "官"], False, 178),
    ("光", "guāng", 1, "light", [], [], True, 178),
    ("广", "guǎng", 3, "wide, broad", [], [], True, 234),
    ("果", "guǒ", 3, "fruit, result", ["木"], ["日", "木"], False, 145),
    ("害", "hài", 4, "to harm, scared", ["宀"], ["宀", "口"], False, 345),
    ("汉", "hàn", 4, "Chinese, man", ["氵"], ["氵", "又"], False, 234),
    ("河", "hé", 2, "river", ["氵"], ["氵", "可"], False, 345),
    ("护", "hù", 4, "to protect", ["扌"], ["扌", "户"], False, 345),
    ("画", "huà", 4, "to draw, painting", ["田"], ["一", "田"], False, 345),
    ("坏", "huài", 4, "bad, broken", ["土"], ["土", "不"], False, 345),
    ("换", "huàn", 4, "to change, exchange", ["扌"], ["扌", "奂"], False, 345),
    ("黄", "huáng", 2, "yellow", [], [], True, 345),
    ("回", "huí", 2, "to return, MW", ["囗"], ["囗", "口"], False, 67),
    ("或", "huò", 4, "or, perhaps", [], [], False, 145),
    ("极", "jí", 2, "extremely, pole", ["木"], ["木", "及"], False, 178),
    ("记", "jì", 4, "to remember, note", ["讠"], ["讠", "己"], False, 178),
    ("季", "jì", 4, "season", ["子"], ["禾", "子"], False, 456),
    ("检", "jiǎn", 3, "to inspect", ["木"], ["木", "佥"], False, 345),
    ("简", "jiǎn", 3, "simple", ["竹"], ["竹", "间"], False, 234),
    ("健", "jiàn", 4, "healthy, strong", ["亻"], ["亻", "建"], False, 345),
    ("见", "jiàn", 4, "to see", [], [], True, 34),
    ("角", "jiǎo", 3, "corner, angle", [], [], True, 345),
    ("脚", "jiǎo", 3, "foot", ["月"], ["月", "却"], False, 456),
    ("接", "jiē", 1, "to receive, connect", ["扌"], ["扌", "妾"], False, 178),
    ("节", "jié", 2, "festival, section", ["艹"], ["艹", "卩"], False, 234),
    ("结", "jié", 2, "to tie, result", ["纟"], ["纟", "吉"], False, 178),
    ("解", "jiě", 3, "to solve, explain", ["角"], ["角", "刀", "牛"], False, 145),
    ("经", "jīng", 1, "to pass through", ["纟"], ["纟", "巠"], False, 45),
    ("久", "jiǔ", 3, "long time", [], [], True, 234),
    ("旧", "jiù", 4, "old (things)", ["日"], ["丨", "日"], False, 345),
    ("举", "jǔ", 3, "to raise, to hold", [], [], False, 234),
    ("句", "jù", 4, "sentence, MW", ["口"], ["勹", "口"], False, 345),
    ("决", "jué", 2, "to decide", ["冫"], ["冫", "夬"], False, 178),
    ("刻", "kè", 4, "quarter hour, to carve", ["刂"], ["亥", "刂"], False, 345),
    ("客", "kè", 4, "guest", ["宀"], ["宀", "各"], False, 234),
    ("空", "kōng", 1, "empty, sky", ["穴"], ["穴", "工"], False, 178),
    ("口", "kǒu", 3, "mouth", [], [], True, 89),
    ("苦", "kǔ", 3, "bitter, hard", ["艹"], ["艹", "古"], False, 456),
    ("裤", "kù", 4, "pants", ["衤"], ["衤", "库"], False, 789),
    ("筷", "kuài", 4, "chopsticks", ["竹"], ["竹", "快"], False, 890),
    ("蓝", "lán", 2, "blue", ["艹"], ["艹", "监"], False, 567),
    ("老", "lǎo", 3, "old (people)", [], [], True, 56),
    ("了", "le", 0, "particle (completed)", [], [], False, 3),
    ("累", "lèi", 4, "tired", ["田"], ["田", "糸"], False, 567),
    ("冷", "lěng", 3, "cold", ["冫"], ["冫", "令"], False, 456),
    ("李", "lǐ", 3, "plum, surname Li", ["木"], ["木", "子"], False, 345),
    ("礼", "lǐ", 3, "ceremony, gift", ["礻"], ["礻", "乚"], False, 345),
    ("力", "lì", 4, "strength, power", [], [], True, 89),
    ("历", "lì", 4, "history, calendar", [], [], False, 234),
    ("练", "liàn", 4, "to practice", ["纟"], ["纟", "柬"], False, 345),
    ("亮", "liàng", 4, "bright", [], [], False, 345),
    ("辆", "liàng", 4, "MW for vehicles", ["车"], ["车", "两"], False, 567),
    ("林", "lín", 2, "forest", ["木"], ["木", "木"], False, 456),
    ("楼", "lóu", 2, "building, floor", ["木"], ["木", "娄"], False, 345),
    ("绿", "lǜ", 4, "green", ["纟"], ["纟", "录"], False, 456),
    ("满", "mǎn", 3, "full", ["氵"], ["氵", "两"], False, 234),
    ("帽", "mào", 4, "hat", ["巾"], ["巾", "冒"], False, 789),
    ("米", "mǐ", 3, "rice, meter", [], [], True, 345),
    ("明", "míng", 2, "bright, clear", ["日"], ["日", "月"], False, 56),
    ("拿", "ná", 2, "to take, to hold", ["扌"], ["合", "手"], False, 345),
    ("奶", "nǎi", 3, "grandmother, milk", ["女"], ["女", "乃"], False, 567),
    ("南", "nán", 2, "south", [], [], True, 178),
    ("难", "nán", 2, "difficult", [], [], False, 178),
    ("年", "nián", 2, "year", [], [], True, 34),
    ("鸟", "niǎo", 3, "bird", [], [], True, 567),
    ("努", "nǔ", 3, "to exert", ["力"], ["奴", "力"], False, 456),
    ("爬", "pá", 2, "to climb", ["爪"], ["爪", "巴"], False, 567),
    ("盘", "pán", 2, "plate, dish", ["皿"], ["舟", "皿"], False, 567),
    ("胖", "pàng", 4, "fat", ["月"], ["月", "半"], False, 678),
    ("皮", "pí", 2, "skin, leather", [], [], True, 345),
    ("啤", "pí", 2, "beer", ["口"], ["口", "卑"], False, 890),
    ("片", "piàn", 4, "piece, slice", [], [], True, 345),
    ("瓶", "píng", 2, "bottle", ["瓦"], ["并", "瓦"], False, 567),
    ("其", "qí", 2, "its, that", [], [], False, 45),
    ("奇", "qí", 2, "strange, wonderful", ["大"], ["大", "可"], False, 345),
    ("骑", "qí", 2, "to ride", ["马"], ["马", "奇"], False, 567),
    ("轻", "qīng", 1, "light (weight)", ["车"], ["车", "巠"], False, 345),
    ("秋", "qiū", 1, "autumn", ["禾"], ["禾", "火"], False, 456),
    ("裙", "qún", 2, "skirt", ["衤"], ["衤", "君"], False, 789),
    ("然", "rán", 2, "so, like that", ["灬"], ["月", "灬"], False, 34),
    ("热", "rè", 4, "hot", ["灬"], ["执", "灬"], False, 345),
    ("认", "rèn", 4, "to recognize", ["讠"], ["讠", "人"], False, 178),
    ("容", "róng", 2, "to contain, face", ["宀"], ["宀", "谷"], False, 234),
    ("如", "rú", 2, "if, like", ["女"], ["女", "口"], False, 89),
    ("伞", "sǎn", 3, "umbrella", ["亻"], ["人", "十"], False, 789),
    ("声", "shēng", 1, "sound, voice", [], [], True, 89),
    ("世", "shì", 4, "world, era", [], [], True, 56),
    ("试", "shì", 4, "to try, test", ["讠"], ["讠", "式"], False, 178),
    ("瘦", "shòu", 4, "thin, skinny", ["疒"], ["疒", "叟"], False, 567),
    ("树", "shù", 4, "tree", ["木"], ["木", "对"], False, 345),
    ("双", "shuāng", 1, "pair, double", ["又"], ["又", "又"], False, 345),
    ("死", "sǐ", 3, "to die, dead", ["歹"], ["歹", "匕"], False, 234),
    ("算", "suàn", 4, "to calculate", ["竹"], ["竹", "目", "廾"], False, 178),
    ("太", "tài", 4, "too, very", [], [], False, 56),
    ("特", "tè", 4, "special", ["牛"], ["牛", "寺"], False, 145),
    ("疼", "téng", 2, "pain, to ache", ["疒"], ["疒", "冬"], False, 567),
    ("提", "tí", 2, "to carry, raise", ["扌"], ["扌", "是"], False, 145),
    ("甜", "tián", 2, "sweet", ["甘"], ["舌", "甘"], False, 678),
    ("听", "tīng", 1, "to listen", ["口"], ["口", "斤"], False, 78),
]

# HSK 4 characters (new in HSK 4, ~150 characters)
HSK4_CHARS = [
    ("爱", "ài", 4, "to love", [], [], False, 56),
    ("按", "àn", 4, "to press, according to", ["扌"], ["扌", "安"], False, 234),
    ("暗", "àn", 4, "dark", ["日"], ["日", "音"], False, 456),
    ("傲", "ào", 4, "proud, arrogant", ["亻"], ["亻", "敖"], False, 678),
    ("本", "běn", 3, "root, this, MW", ["木"], ["木", "一"], False, 45),
    ("笔", "bǐ", 3, "pen, writing tool", ["竹"], ["竹", "毛"], False, 345),
    ("毕", "bì", 4, "to finish, complete", [], [], False, 345),
    ("必", "bì", 4, "must, certainly", [], [], True, 89),
    ("遍", "biàn", 4, "MW for times", ["辶"], ["辶", "扁"], False, 456),
    ("标", "biāo", 1, "mark, sign", ["木"], ["木", "示"], False, 345),
    ("博", "bó", 2, "extensive, to win", ["十"], ["十", "尃"], False, 345),
    ("补", "bǔ", 3, "to mend, supplement", ["衤"], ["衤", "卜"], False, 456),
    ("不", "bù", 4, "not", [], [], True, 4),
    ("部", "bù", 4, "part, department", ["阝"], ["立", "阝"], False, 78),
    ("猜", "cāi", 1, "to guess", ["犭"], ["犭", "青"], False, 678),
    ("材", "cái", 2, "material", ["木"], ["木", "才"], False, 345),
    ("参", "cān", 1, "to participate", [], [], False, 234),
    ("餐", "cān", 1, "meal", ["食"], ["食", "又"], False, 456),
    ("厕", "cè", 4, "toilet", ["厂"], ["厂", "则"], False, 789),
    ("曾", "céng", 2, "once, ever", [], [], False, 234),
    ("尝", "cháng", 2, "to taste, to try", ["口"], ["尚", "口"], False, 567),
    ("场", "chǎng", 3, "field, venue", ["土"], ["土", "昜"], False, 178),
    ("称", "chēng", 1, "to call, weigh", ["禾"], ["禾", "尔"], False, 345),
    ("诚", "chéng", 2, "honest, sincere", ["讠"], ["讠", "成"], False, 456),
    ("抽", "chōu", 1, "to draw out, smoke", ["扌"], ["扌", "由"], False, 456),
    ("丑", "chǒu", 3, "ugly", [], [], False, 678),
    ("初", "chū", 1, "beginning, first", ["刂"], ["衤", "刂"], False, 234),
    ("传", "chuán", 2, "to pass, legend", ["亻"], ["亻", "专"], False, 145),
    ("窗", "chuāng", 1, "window", ["穴"], ["穴", "囱"], False, 456),
    ("此", "cǐ", 3, "this", [], [], True, 89),
    ("促", "cù", 4, "to urge, promote", ["亻"], ["亻", "足"], False, 456),
    ("存", "cún", 2, "to exist, save", [], [], False, 234),
    ("达", "dá", 2, "to reach, achieve", ["辶"], ["辶", "大"], False, 145),
    ("代", "dài", 4, "generation, era", ["亻"], ["亻", "弋"], False, 145),
    ("导", "dǎo", 3, "to guide, lead", ["寸"], ["巳", "寸"], False, 234),
    ("倒", "dào", 4, "to fall, pour", ["亻"], ["亻", "到"], False, 234),
    ("德", "dé", 2, "virtue, morals", ["彳"], ["彳", "心"], False, 178),
    ("底", "dǐ", 3, "bottom", ["广"], ["广", "氐"], False, 234),
    ("点", "diǎn", 3, "dot, point, o'clock", ["灬"], ["占", "灬"], False, 34),
    ("掉", "diào", 4, "to drop, fall", ["扌"], ["扌", "卓"], False, 345),
    ("丢", "diū", 1, "to lose, throw", [], [], False, 567),
    ("度", "dù", 4, "degree, measure", ["广"], ["广", "又"], False, 145),
    ("堵", "dǔ", 3, "to block", ["土"], ["土", "者"], False, 678),
    ("断", "duàn", 4, "to break, decide", [], [], False, 178),
    ("队", "duì", 4, "team, line", ["阝"], ["阝", "人"], False, 234),
    ("顿", "dùn", 4, "MW for meals, pause", ["页"], ["屯", "页"], False, 456),
    ("朵", "duǒ", 3, "MW for flowers", ["木"], ["几", "木"], False, 678),
    ("而", "ér", 2, "and, but", [], [], True, 12),
    ("烦", "fán", 2, "annoyed", ["火"], ["火", "页"], False, 567),
    ("反", "fǎn", 3, "opposite, to turn", [], [], True, 89),
    ("范", "fàn", 4, "model, pattern", ["艹"], ["艹", "氾"], False, 456),
    ("丰", "fēng", 1, "rich, abundant", [], [], True, 345),
    ("风", "fēng", 1, "wind", [], [], True, 89),
    ("否", "fǒu", 3, "not, deny", [], [], False, 178),
    ("复", "fù", 4, "to return, complex", [], [], False, 89),
    ("富", "fù", 4, "rich, wealthy", ["宀"], ["宀", "畐"], False, 345),
    ("改", "gǎi", 3, "to change, correct", ["攵"], ["己", "攵"], False, 145),
    ("概", "gài", 4, "approximate", ["木"], ["木", "既"], False, 345),
    ("敢", "gǎn", 3, "to dare", ["攵"], ["耳", "攵"], False, 345),
    ("钢", "gāng", 1, "steel", ["钅"], ["钅", "冈"], False, 456),
    ("格", "gé", 2, "style, standard", ["木"], ["木", "各"], False, 178),
    ("各", "gè", 4, "each, every", [], [], True, 78),
    ("工", "gōng", 1, "work, worker", [], [], True, 34),
    ("功", "gōng", 1, "merit, skill", ["力"], ["工", "力"], False, 178),
    ("估", "gū", 1, "to estimate", ["亻"], ["亻", "古"], False, 456),
    ("故", "gù", 4, "reason, old", ["攵"], ["古", "攵"], False, 178),
    ("顾", "gù", 4, "to look after", ["页"], ["雇", "页"], False, 345),
    ("挂", "guà", 4, "to hang", ["扌"], ["扌", "卦"], False, 456),
    ("怪", "guài", 4, "strange, to blame", ["忄"], ["忄", "圣"], False, 456),
    ("观", "guān", 1, "to watch, view", ["见"], ["又", "见"], False, 145),
    ("惯", "guàn", 4, "accustomed", ["忄"], ["忄", "贯"], False, 345),
    ("规", "guī", 1, "rule, regulation", ["见"], ["夫", "见"], False, 234),
    ("国", "guó", 2, "country, nation", ["囗"], ["囗", "玉"], False, 12),
    ("海", "hǎi", 3, "sea, ocean", ["氵"], ["氵", "每"], False, 145),
    ("航", "háng", 2, "to navigate, flight", ["舟"], ["舟", "亢"], False, 456),
    ("好", "hào", 4, "to like (hobby)", ["女"], ["女", "子"], False, 36),
    ("合", "hé", 2, "to combine, suit", [], [], True, 56),
    ("恨", "hèn", 4, "to hate", ["忄"], ["忄", "艮"], False, 567),
    ("互", "hù", 4, "mutual", [], [], False, 234),
    ("怀", "huái", 2, "to miss, bosom", ["忄"], ["忄", "不"], False, 345),
    ("环", "huán", 2, "ring, environment", ["王"], ["王", "不"], False, 345),
    ("活", "huó", 2, "to live, alive", ["氵"], ["氵", "舌"], False, 89),
    ("获", "huò", 4, "to obtain", ["犭"], ["犭", "蒦"], False, 234),
    ("积", "jī", 1, "to accumulate", ["禾"], ["禾", "只"], False, 234),
    ("及", "jí", 2, "to reach, and", [], [], True, 45),
    ("急", "jí", 2, "urgent, anxious", ["忄"], ["刍", "心"], False, 234),
    ("集", "jí", 2, "to gather, set", ["隹"], ["隹", "木"], False, 178),
    ("技", "jì", 4, "skill, technique", ["扌"], ["扌", "支"], False, 234),
    ("继", "jì", 4, "to continue", ["纟"], ["纟", "米"], False, 234),
    ("加", "jiā", 1, "to add, plus", ["力"], ["口", "力"], False, 56),
    ("假", "jiǎ", 3, "false, vacation", ["亻"], ["亻", "叚"], False, 234),
    ("价", "jià", 4, "price, value", ["亻"], ["亻", "介"], False, 145),
    ("坚", "jiān", 1, "firm, hard", ["土"], ["土", "又"], False, 234),
    ("减", "jiǎn", 3, "to reduce", ["冫"], ["冫", "咸"], False, 345),
    ("建", "jiàn", 4, "to build", ["廴"], ["廴", "聿"], False, 89),
    ("将", "jiāng", 1, "will, about to", ["寸"], ["丬", "寸"], False, 56),
    ("交", "jiāo", 1, "to hand over", [], [], True, 89),
    ("降", "jiàng", 4, "to descend, lower", ["阝"], ["阝", "夅"], False, 234),
    ("饺", "jiǎo", 3, "dumpling", ["食"], ["食", "交"], False, 789),
    ("精", "jīng", 1, "fine, spirit", ["米"], ["米", "青"], False, 145),
    ("竟", "jìng", 4, "unexpectedly", ["立"], ["立", "兄"], False, 345),
    ("竞", "jìng", 4, "to compete", ["立"], ["立", "兄"], False, 345),
    ("镜", "jìng", 4, "mirror", ["钅"], ["钅", "竟"], False, 567),
    ("究", "jiū", 1, "to investigate", ["穴"], ["穴", "九"], False, 178),
    ("居", "jū", 1, "to reside", ["尸"], ["尸", "古"], False, 234),
    ("具", "jù", 4, "tool, to possess", ["八"], ["目", "八"], False, 178),
    ("据", "jù", 4, "according to", ["扌"], ["扌", "居"], False, 145),
    ("均", "jūn", 1, "even, equal", ["土"], ["土", "匀"], False, 345),
    ("看", "kàn", 4, "to look, to see", ["目"], ["手", "目"], False, 23),
    ("科", "kē", 1, "science, subject", ["禾"], ["禾", "斗"], False, 89),
    ("肯", "kěn", 3, "willing, to agree", ["月"], ["止", "月"], False, 345),
    ("恐", "kǒng", 3, "afraid, fear", ["忄"], ["巩", "心"], False, 345),
]

# HSK 5 characters (new in HSK 5, ~150 characters)
HSK5_CHARS = [
    ("哎", "āi", 1, "alas, hey", ["口"], ["口", "艾"], False, 678),
    ("矮", "ǎi", 3, "short (height)", ["矢"], ["矢", "委"], False, 789),
    ("案", "àn", 4, "case, desk", ["木"], ["安", "木"], False, 345),
    ("熬", "áo", 2, "to endure, stew", ["灬"], ["敖", "灬"], False, 789),
    ("悲", "bēi", 1, "sad, sorrowful", ["忄"], ["非", "心"], False, 456),
    ("背", "bèi", 4, "back, to carry", ["月"], ["北", "月"], False, 345),
    ("辈", "bèi", 4, "generation", ["车"], ["非", "车"], False, 567),
    ("逼", "bī", 1, "to force, compel", ["辶"], ["辶", "畐"], False, 678),
    ("臂", "bì", 4, "arm", ["月"], ["辟", "月"], False, 789),
    ("避", "bì", 4, "to avoid", ["辶"], ["辶", "辟"], False, 456),
    ("编", "biān", 1, "to edit, weave", ["纟"], ["纟", "扁"], False, 345),
    ("辩", "biàn", 4, "to debate", ["讠"], ["辛", "讠"], False, 456),
    ("彼", "bǐ", 3, "that, those", ["彳"], ["彳", "皮"], False, 456),
    ("冰", "bīng", 1, "ice", ["冫"], ["冫", "水"], False, 345),
    ("播", "bō", 1, "to broadcast", ["扌"], ["扌", "番"], False, 456),
    ("脖", "bó", 2, "neck", ["月"], ["月", "孛"], False, 789),
    ("财", "cái", 2, "wealth, fortune", ["贝"], ["贝", "才"], False, 345),
    ("采", "cǎi", 3, "to pick, gather", [], [], True, 345),
    ("彩", "cǎi", 3, "colorful", ["彡"], ["采", "彡"], False, 345),
    ("操", "cāo", 1, "to operate, drill", ["扌"], ["扌", "品", "木"], False, 345),
    ("册", "cè", 4, "book, MW", [], [], True, 567),
    ("测", "cè", 4, "to measure, test", ["氵"], ["氵", "则"], False, 345),
    ("插", "chā", 1, "to insert", ["扌"], ["扌", "臿"], False, 456),
    ("拆", "chāi", 1, "to tear down", ["扌"], ["扌", "斥"], False, 567),
    ("产", "chǎn", 3, "to produce", [], [], False, 56),
    ("尝", "cháng", 2, "to taste, try", ["口"], ["尚", "口"], False, 456),
    ("常", "cháng", 2, "often, common", ["巾"], ["尚", "巾"], False, 78),
    ("吵", "chǎo", 3, "noisy, quarrel", ["口"], ["口", "少"], False, 567),
    ("沉", "chén", 2, "to sink, deep", ["氵"], ["氵", "冗"], False, 345),
    ("趁", "chèn", 4, "to take advantage", ["走"], ["走", "珍"], False, 567),
    ("承", "chéng", 2, "to bear, accept", [], [], False, 178),
    ("程", "chéng", 2, "journey, process", ["禾"], ["禾", "呈"], False, 145),
    ("吃", "chī", 1, "to eat", ["口"], ["口", "乞"], False, 89),
    ("冲", "chōng", 1, "to rush, rinse", ["冫"], ["冫", "中"], False, 345),
    ("宠", "chǒng", 3, "to spoil, pet", ["宀"], ["宀", "龙"], False, 678),
    ("愁", "chóu", 2, "to worry, sad", ["忄"], ["秋", "心"], False, 567),
    ("臭", "chòu", 4, "smelly, stinky", [], [], False, 678),
    ("创", "chuàng", 4, "to create", ["刂"], ["仓", "刂"], False, 234),
    ("纯", "chún", 2, "pure", ["纟"], ["纟", "屯"], False, 456),
    ("辞", "cí", 2, "to resign, word", ["辛"], ["舌", "辛"], False, 456),
    ("刺", "cì", 4, "to stab, thorn", ["刂"], ["朿", "刂"], False, 567),
    ("匆", "cōng", 1, "hurried", ["勹"], ["勹", "丿"], False, 678),
    ("催", "cuī", 1, "to urge, press", ["亻"], ["亻", "崔"], False, 567),
    ("脆", "cuì", 4, "crispy, brittle", ["月"], ["月", "危"], False, 678),
    ("措", "cuò", 4, "to arrange, measure", ["扌"], ["扌", "昔"], False, 456),
    ("答", "dā", 1, "to respond", ["竹"], ["竹", "合"], False, 234),
    ("呆", "dāi", 1, "foolish, stunned", ["口"], ["口", "木"], False, 678),
    ("贷", "dài", 4, "to lend, loan", ["贝"], ["代", "贝"], False, 456),
    ("胆", "dǎn", 3, "gall, courage", ["月"], ["月", "旦"], False, 567),
    ("淡", "dàn", 4, "bland, light", ["氵"], ["氵", "炎"], False, 456),
    ("弹", "dàn", 4, "bullet, to play", ["弓"], ["弓", "单"], False, 345),
    ("盗", "dào", 4, "to steal, thief", ["皿"], ["次", "皿"], False, 567),
    ("递", "dì", 4, "to pass, deliver", ["辶"], ["辶", "弟"], False, 456),
    ("典", "diǎn", 3, "dictionary, classic", [], [], False, 345),
    ("电", "diàn", 4, "electricity", [], [], True, 34),
    ("钓", "diào", 4, "to fish (with rod)", ["钅"], ["钅", "勺"], False, 789),
    ("冻", "dòng", 4, "to freeze", ["冫"], ["冫", "东"], False, 567),
    ("洞", "dòng", 4, "hole, cave", ["氵"], ["氵", "同"], False, 456),
    ("豆", "dòu", 4, "bean", [], [], True, 567),
    ("逗", "dòu", 4, "to tease, amuse", ["辶"], ["辶", "豆"], False, 678),
    ("独", "dú", 2, "alone, single", ["犭"], ["犭", "虫"], False, 234),
    ("端", "duān", 1, "end, to hold", ["立"], ["立", "耑"], False, 345),
    ("兑", "duì", 4, "to exchange", [], [], False, 567),
    ("吨", "dūn", 1, "ton", ["口"], ["口", "屯"], False, 789),
    ("蹲", "dūn", 1, "to squat", ["足"], ["足", "尊"], False, 789),
    ("顿", "dùn", 4, "MW for meals", ["页"], ["屯", "页"], False, 456),
    ("夺", "duó", 2, "to seize, compete", [], [], False, 456),
    ("恶", "è", 4, "evil, bad", ["忄"], ["亚", "心"], False, 345),
    ("耳", "ěr", 3, "ear", [], [], True, 345),
    ("罚", "fá", 2, "to punish, fine", ["罒"], ["罒", "言"], False, 456),
    ("法", "fǎ", 3, "law, method", ["氵"], ["氵", "去"], False, 23),
    ("翻", "fān", 1, "to turn over", ["羽"], ["番", "羽"], False, 345),
    ("繁", "fán", 2, "complex, numerous", ["纟"], ["敏", "糸"], False, 345),
    ("烦", "fán", 2, "annoyed, bother", ["火"], ["火", "页"], False, 456),
    ("犯", "fàn", 4, "to commit (crime)", ["犭"], ["犭", "㔾"], False, 345),
    ("泛", "fàn", 4, "to float, general", ["氵"], ["氵", "乏"], False, 456),
    ("肺", "fèi", 4, "lung", ["月"], ["月", "巿"], False, 678),
    ("废", "fèi", 4, "waste, useless", ["广"], ["广", "发"], False, 456),
    ("纷", "fēn", 1, "numerous, confused", ["纟"], ["纟", "分"], False, 456),
    ("愤", "fèn", 4, "angry, indignant", ["忄"], ["忄", "贲"], False, 567),
    ("缝", "féng", 2, "to sew, seam", ["纟"], ["纟", "逢"], False, 567),
    ("佛", "fó", 2, "Buddha", ["亻"], ["亻", "弗"], False, 567),
    ("扶", "fú", 2, "to support", ["扌"], ["扌", "夫"], False, 456),
    ("符", "fú", 2, "symbol, talisman", ["竹"], ["竹", "付"], False, 456),
    ("幅", "fú", 2, "MW for paintings", ["巾"], ["巾", "畐"], False, 567),
    ("辅", "fǔ", 3, "to assist", ["车"], ["车", "甫"], False, 567),
    ("妇", "fù", 4, "woman, wife", ["女"], ["女", "彐"], False, 345),
    ("赴", "fù", 4, "to go to", ["走"], ["走", "卜"], False, 567),
    ("覆", "fù", 4, "to cover, overturn", ["覀"], ["覀", "复"], False, 456),
    ("甘", "gān", 1, "sweet, willing", [], [], True, 567),
    ("赶", "gǎn", 3, "to hurry, catch up", ["走"], ["走", "干"], False, 234),
    ("岗", "gǎng", 3, "hill, post", ["山"], ["山", "冈"], False, 567),
    ("搞", "gǎo", 3, "to do, make", ["扌"], ["扌", "高"], False, 234),
    ("告", "gào", 4, "to tell, accuse", ["口"], ["牛", "口"], False, 178),
    ("隔", "gé", 2, "to separate", ["阝"], ["阝", "鬲"], False, 345),
    ("个", "gè", 4, "MW (general)", [], [], False, 6),
    ("根", "gēn", 1, "root, MW", ["木"], ["木", "艮"], False, 178),
    ("耕", "gēng", 1, "to plow", ["耒"], ["耒", "井"], False, 678),
    ("贡", "gòng", 4, "to tribute", ["贝"], ["工", "贝"], False, 567),
    ("沟", "gōu", 1, "ditch, groove", ["氵"], ["氵", "勾"], False, 567),
    ("构", "gòu", 4, "to construct", ["木"], ["木", "勾"], False, 234),
    ("鼓", "gǔ", 3, "drum, to beat", [], [], True, 456),
    ("骨", "gǔ", 3, "bone", [], [], True, 345),
    ("固", "gù", 4, "solid, firm", ["囗"], ["囗", "古"], False, 234),
    ("拐", "guǎi", 3, "to turn, abduct", ["扌"], ["扌", "另"], False, 678),
    ("冠", "guān", 1, "crown, hat", ["冖"], ["冖", "元", "寸"], False, 456),
    ("灌", "guàn", 4, "to pour, irrigate", ["氵"], ["氵", "雚"], False, 567),
    ("棍", "gùn", 4, "stick, rod", ["木"], ["木", "昆"], False, 789),
    ("锅", "guō", 1, "pot, pan", ["钅"], ["钅", "呙"], False, 567),
]

# Expanded radical data (40+ high-frequency radicals)
RADICALS = [
    {"radical": "氵", "meaning": "water", "display_name": "Water (three drops)"},
    {"radical": "讠", "meaning": "speech", "display_name": "Speech"},
    {"radical": "忄", "meaning": "heart, emotion", "display_name": "Heart (standing)"},
    {"radical": "扌", "meaning": "hand", "display_name": "Hand"},
    {"radical": "口", "meaning": "mouth", "display_name": "Mouth"},
    {"radical": "女", "meaning": "woman", "display_name": "Woman"},
    {"radical": "木", "meaning": "wood, tree", "display_name": "Wood"},
    {"radical": "辶", "meaning": "walk, movement", "display_name": "Walk"},
    {"radical": "亻", "meaning": "person", "display_name": "Person (standing)"},
    {"radical": "日", "meaning": "sun, day", "display_name": "Sun"},
    {"radical": "月", "meaning": "moon, flesh", "display_name": "Moon / Flesh"},
    {"radical": "土", "meaning": "earth", "display_name": "Earth"},
    {"radical": "纟", "meaning": "silk, thread", "display_name": "Silk"},
    {"radical": "竹", "meaning": "bamboo", "display_name": "Bamboo"},
    {"radical": "宀", "meaning": "roof, shelter", "display_name": "Roof"},
    {"radical": "火", "meaning": "fire", "display_name": "Fire"},
    {"radical": "灬", "meaning": "fire (dots)", "display_name": "Fire (four dots)"},
    {"radical": "足", "meaning": "foot", "display_name": "Foot"},
    {"radical": "目", "meaning": "eye", "display_name": "Eye"},
    {"radical": "刂", "meaning": "knife", "display_name": "Knife (right)"},
    {"radical": "力", "meaning": "strength", "display_name": "Strength"},
    {"radical": "攵", "meaning": "strike, tap", "display_name": "Strike"},
    {"radical": "禾", "meaning": "grain", "display_name": "Grain"},
    {"radical": "艹", "meaning": "grass, plant", "display_name": "Grass"},
    {"radical": "冫", "meaning": "ice", "display_name": "Ice"},
    {"radical": "穴", "meaning": "cave, hole", "display_name": "Cave"},
    {"radical": "衤", "meaning": "clothing", "display_name": "Clothing"},
    {"radical": "见", "meaning": "to see", "display_name": "See"},
    {"radical": "贝", "meaning": "shell, money", "display_name": "Shell"},
    {"radical": "车", "meaning": "vehicle", "display_name": "Vehicle"},
    {"radical": "阝", "meaning": "hill, city wall", "display_name": "Hill / City"},
    {"radical": "页", "meaning": "page, head", "display_name": "Page / Head"},
    {"radical": "钅", "meaning": "metal, gold", "display_name": "Metal"},
    {"radical": "食", "meaning": "food, eat", "display_name": "Food"},
    {"radical": "犭", "meaning": "animal", "display_name": "Animal"},
    {"radical": "疒", "meaning": "sickness", "display_name": "Sickness"},
    {"radical": "走", "meaning": "to run", "display_name": "Run"},
    {"radical": "囗", "meaning": "enclosure", "display_name": "Enclosure"},
    {"radical": "广", "meaning": "wide, shelter", "display_name": "Wide Shelter"},
    {"radical": "彳", "meaning": "step (left)", "display_name": "Step"},
    {"radical": "舟", "meaning": "boat", "display_name": "Boat"},
    {"radical": "鬼", "meaning": "ghost, demon", "display_name": "Ghost"},
    {"radical": "龙", "meaning": "dragon", "display_name": "Dragon"},
    {"radical": "鸟", "meaning": "bird", "display_name": "Bird"},
    {"radical": "马", "meaning": "horse", "display_name": "Horse"},
]


def build_character_entry(char_tuple, hsk_level):
    char, pinyin, tone, meaning, radicals, components, is_radical, freq = char_tuple
    return {
        "character": char,
        "pinyin": pinyin,
        "tone": tone,
        "meaning": meaning,
        "hsk_level": hsk_level,
        "radicals": radicals,
        "components": components,
        "is_radical": is_radical,
        "frequency_rank": freq,
    }


def build_radical_entry(radical_def, all_chars):
    """Build a radical entry with its character list from the full dataset."""
    rad = radical_def["radical"]
    chars = []
    for c in all_chars:
        if rad in c["radicals"]:
            chars.append(c["character"])
    return {
        "radical": rad,
        "meaning": radical_def["meaning"],
        "characters": chars,
        "display_name": radical_def["display_name"],
    }


def build_radical_character_map(all_chars):
    """Build the radical -> characters mapping."""
    mapping = {"_description": "Maps each radical to all HSK 2-5 characters containing it."}
    for c in all_chars:
        for rad in c["radicals"]:
            if rad not in mapping:
                mapping[rad] = []
            if c["character"] not in mapping[rad]:
                mapping[rad].append(c["character"])
    return mapping


def main():
    base_dir = os.path.join(os.path.dirname(__file__), "..", "godot-project", "data")

    # Build all character entries
    all_chars = []
    datasets = [
        (HSK2_CHARS, 2, "hsk2"),
        (HSK3_CHARS, 3, "hsk3"),
        (HSK4_CHARS, 4, "hsk4"),
        (HSK5_CHARS, 5, "hsk5"),
    ]

    for chars, level, dirname in datasets:
        entries = [build_character_entry(c, level) for c in chars]
        all_chars.extend(entries)

        out_dir = os.path.join(base_dir, dirname)
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "characters.json")
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(entries, f, ensure_ascii=False, indent=2)
        print(f"  {dirname}/characters.json: {len(entries)} characters")

    print(f"Total characters: {len(all_chars)}")

    # Build radical data
    rad_dir = os.path.join(base_dir, "radicals")
    os.makedirs(rad_dir, exist_ok=True)

    radical_entries = [build_radical_entry(r, all_chars) for r in RADICALS]
    # Only keep radicals that have at least one character
    radical_entries = [r for r in radical_entries if r["characters"]]

    with open(os.path.join(rad_dir, "radicals.json"), "w", encoding="utf-8") as f:
        json.dump(radical_entries, f, ensure_ascii=False, indent=2)
    print(f"  radicals/radicals.json: {len(radical_entries)} radicals")

    # Build radical-character map
    rad_map = build_radical_character_map(all_chars)
    with open(os.path.join(rad_dir, "radical_character_map.json"), "w", encoding="utf-8") as f:
        json.dump(rad_map, f, ensure_ascii=False, indent=2)
    rad_count = len([k for k in rad_map if k != "_description"])
    print(f"  radicals/radical_character_map.json: {rad_count} radicals mapped")


if __name__ == "__main__":
    main()
